Add issue template forms
appwrite/php-runtimes pull request #19
Opened 2021-10-01 07:19 UTC by Sven65

Closes #18

 [x] Fork & clone this repository
 [x] Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 [x] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml
 [x] Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 [x] Push changes to master and test issue forms on your fork
 [x] Submit pull request

2021-10-03 10:35 UTC, lohanidamodar commented
@Sven65  Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

2021-10-04 06:47 UTC, Sven65 commented
Thanks @lohanidamodar! I've added the missing code of conduct checks!

2021-10-04 07:49 UTC, lohanidamodar requested changes
@Sven65 great job. Small changes to make it consistent 👍🏻

2021-10-04 07:49 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "🎲 Appwrite version"
We can remove this.

2021-10-04 07:49 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +    id: appwrite-runtimes-version
```suggestion
    id: php-runtimes-version
```

2021-10-04 07:49 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "🎲 Appwrite Runtimes version"
```suggestion
      label: "🎲 PHP Runtimes version"
```

2021-10-04 07:49 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      description: "What version of Appwrite Runtimes are you running?"
```suggestion
      description: "What version of PHP Runtimes are you running?"
```

2021-10-31 07:27 UTC, christyjacob4 commented
@Sven65  Let us know if you're still working on this

2021-11-01 08:18 UTC, Sven65 commented
I thought I had submitted the fixes, but apparently not, will do.

2021-11-03 05:02 UTC, lohanidamodar approved these changes

2021-11-17 07:33 UTC, merged

2021-11-17 07:33 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)